### ISSUE TITLE
[Feature Request] Enable the devtools in production

### ISSUE THREAD

**Issue by soufiene-slimi** [Laravel-Backpack/devtools-issues#13]
# Feature Request

### What's the feature you think DevTools should have?

Maybe a config key to enable or disable the **devtools** in production, and by default devtools is disabled in a production environment.
```php

// file: config/backpack/devtools.php
return [
    //...

    'enable_in_production' => env('BACKPACK_DEVTOOLS_ENABLE_IN_PRODUCTION', false),
];
```

### How often do you see yourself using this feature, if implemented?

Some projects need to be tested in production mode on the developer's machine, and switching between **local** and **production** while developing a new module or adding some data using the devtools can be painful.
So by default, the devtools **MUST** not work in a production mode, and if we enable the devtools while in production some commands needs to be updated, for example, the `php artisan migrate` will become `php artisan migrate --force`, or maybe a prompt will appear to confirm the execution of the action.

**Comment by promatik** [comment]
Hi @soufiene-slimi!
The truth is, it works in production mode, but by default two things happen;
- DevTools recommends devs to install it using `--dev` arg, so it will not be installed in production.
- DevTools will also create the sidebar entry with the condition `@if (app()->environment('local'))`.

So the sidebar entry is what makes DevTools only available on Local env, but developers can easily change this.

**Anyway**, I think we could add that config, it wouldn't hurt and along adding the 
```php
@if (in_array(config('devtools.env'), app()->environment()))
```
on the sidebar, we could validate (deny/allow) the access on the controller depending on this config, it would be an extra level of security.

@pxpm, @tabacitu let me know what you think ✌

**Comment by tabacitu** [comment]
Hmmm... that's interesting. Never thought devs might use `APP_ENV=production` on localhost, but... I see why they might do that, you make a good point @soufiene-slimi . Yes I think we can support this.

Perhaps we should:

1. Show the sidebar item by checking if the DevTools project is installed, rather than if the ENV is local:
```diff
-@if (app()->environment('local'))
+@if (\Composer\InstalledVersions::isInstalled('backpack/devtools'))
```
BUT that would only work if the dev has Composer 2 installed... So we'd also need a fallback in case `\Composer\InstalledVersions` doesn't exist... probably `app()->environment('local')` 😅

2. Show a big warning sign on all DevTools pages if running it in production. Saying you shouldn't do that. @promatik suggested this in a different issue, I agree with it.

3. Run the migrations with `--force` anyway. I don't see any harm in that... right?!

**Comment by soufiene-slimi** [comment]
@tabacitu If we generate a new release for a product, we have to test the patch locally, a similar environment to the production server is highly recommend to avoid problems 😸

**Comment by tabacitu** [comment]
@soufiene-slimi I'm happy to tell you that we've finished [the PR for this](https://github.com/Laravel-Backpack/DevTools/pull/256) and we'll be merging it this week. No flag, no config, no nothing, it'll just work in production, as you'd expect. So watch out for the next version - it's now in the last stages of approval. 

Thanks for telling us about this - personally I wouldn't have thought of this 🙏
I'll close the issue since we have a PR for it, that will be merged soon. 
Cheers!
