### ISSUE TITLE
Can't install backpack/devtools with composer [Bug] 

### ISSUE THREAD

**Issue by Nejedlos** [Laravel-Backpack/devtools-issues#15]
# Bug report

When I try to install backpack/devtools with composer ( composer require --dev --with-all-dependencies backpack/devtools ) it give me this exception:  
[InvalidArgumentException]                                                                                                                                                           
  Could not find a matching version of package backpack/devtools. Check the package spelling, your version constraint and that the package is available in a stability which matches   
  your minimum-stability (dev).  

Few days ago all worked perfectly (authentication with token and then installation)

Is any problem on the source or is the problem on my side?

**Comment by promatik** [comment]
Hi @Nejedlos!

I tried in both Windows and Ubuntu, and I was able to install DevTools.
Even after clearing composer cache. 

At a first glance I have no idea of what could be causing it, internet says this happens when the package has no published tags, but that's not the case.

Can you try to run it again? Maybe it was a temporary fail of the server(?)
If you still have the error, can you try to run it without the `--with-all-dependencies` – `composer require --dev backpack/devtools`
And if nothing of this works, can you try to clear composer cache by running `composer clearcache`?

Sorry for asking so much 😅 I would like to be able to help you in a more precise way.
Thank you.

**Comment by Nejedlos** [comment]
Thank you for your advices, seems that problem was in phpstorm terminal. After update phpstorm everything seems OK.
