### ISSUE TITLE
[Feature Request] I will stop my version ( but will try to list what i wanted )

### ISSUE THREAD

**Issue by iMokhles** [Laravel-Backpack/devtools-issues#3]
I was working on something similar but didn't expect that there will be official version
https://github.com/iMokhles/gui-for-backpack repo was empty here local is full of some functionalities
i started the road but i was a little bit slow :) i will discontinue my version and of course i will buy your version
you guys doing a great work and Nice work in this devtools

and What Feature i need in Laravel for Backpack is this Pull request ( https://github.com/Laravel-Backpack/CRUD/pull/3420 )
@tabacitu please if you have time check it ;)

and again Excellent Job in those DevTools

**Comment by tabacitu** [comment]
Hello again @iMokhles ,

Ugh... 👀  I had no idea you were working on this too - sorry @iMokhles . Please know we didn't do anything like "_steal your idea_", or steal your code, or anything like that - we're good people here. DevTools has been planned for _years_, we just never had time to build the first version until about 6-8 months ago. I promise - no funny business here. It's been a major moral blow when Taylor released Nova (even though they had all the right to do so), so I wouldn't want to inflict the same kind of disappointment onto anyone. Again - sorry if this makes you feel betrayed or anything like that, we really didn't mean anything by this... and had no idea you were working on it 😔 Again, very sorry for any negative feelings towards us because of this...

On a lighter note, It's probably better that you didn't finish or publish it 😅  We thought it'd take us 1 month and took us a lot more (like 6-8 months) soo... yeah. This wouldn't have worked as a free product - too much work to be all done for free. You were probably in the same boat, this thing was more difficult to code than expected - a lot of moving parts and conditionals, to get it to behave as you'd expect. And we're still far from our "perfect version", it'll probably take one more year to get it "just right". Tough cookie.

> a dream will become true soon

I hope it has! 😅. Or will become soon, we have a lot of features we want to cram into DevTools, and we're open to suggestions. 

----

Let's move this in a productive direction here:
- I've tagged https://github.com/Laravel-Backpack/CRUD/pull/3420 as a MUST-DO and we'll get it marged/polished/done in the next few months, for Backpack 4.2; thank you 🙏
- I'm eager to see what you had built in your GUI, what features you had in mind; let us know, please;
- I think it's about time we get to meet each other too - what do you say we schedule a Google Meet next week? if you're up to it, please shoot me an email at cristian.tabacitu@backpackforlaravel.com and let's finally see each other 😉. should be easier for you to show me your GUI that way too;
- do NOT freaking buy DevTools 😅  you'll get free access, it's the least we can do for all the help you've been giving to the Backpack community 😀. I'll issue a token for you once I have your email;

Cheers!
