### ISSUE TITLE
[Bug] Data loss when two fields have same name

### ISSUE THREAD

**Issue by Polfo** [Laravel-Backpack/devtools-issues#30]
# Bug report

### What I did

Defined a new table where two fields accidentally have the same name, then hit Save and Back

### What I expected to happen

Error message

### What happened

Returned empty form, all data is lost.

### PHP VERSION:
PHP 8.0.2 (cli) (built: Feb  3 2021 18:36:40) ( ZTS Visual C++ 2019 x64 )
Copyright (c) The PHP Group
Zend Engine v4.0.2, Copyright (c) Zend Technologies
    with Zend OPcache v8.0.2, Copyright (c), by Zend Technologies

### LARAVEL VERSION:
v8.74.0@004ea195012d5132eca07a176a6e587c6a74815e

### BACKPACK VERSION:
4.1.61@4400187391eb5b73672c2b166a990cd737277409

### Operating System and Server Setup

I encountered the problem above on my [Windows 10] machine, and my web server is set up using [php artisan serve].

**Comment by tabacitu** [comment]
Hey @Polfo ,

This has nothing to do with DevTools, so I'm going to move the issue to CRUD.

This is the expected behaviour. You cannot have two fields with the same name. Think of fields as inputs. You can't have two HTML inputs with the same name in a form, can you? Because the second one would overwrite the value of the first one. That's exactly what happens here - adding two fields with the same name just doesn't make sense, Backpack/Laravel has no way of knowing which value you prefer. They have to have different names. 

There are more issues in this repo with the same thing - we don't plan to add support for multiple fields with the same name in the future.

Cheers!
