### ISSUE TITLE
[Feature Request] Let the addon be Semi-Open/Closed Source

### ISSUE THREAD

**Issue by Aniruddh-J** [Laravel-Backpack/devtools-issues#34]
# Feature Request

### What's the feature you think DevTools should have?

It would be great if devs allow access to the protected repo to those who purchased the addon. And let those people submit PRs. :)

### How often do you see yourself using this feature, if implemented?

Quite often. I'd be willing to help with the development of this tool because I see a huge potential in it.

**Comment by tabacitu** [comment]
I'd love that - tried it a bunch of ways. But unfortunately:
- we can't public-source it, because we've learnt our lesson with Backpack, where 99% of usage is unpaid;
- if we invite people to the closed-source repo, every collaborator would become a monthly cost... that's the only way Github private repos work (and we can't blame them, they have to make money);

So for now... unfortunately... no PRs... sorry. If Github policy ever changes, or you see a different way where we can give access to buyers (but without the monthly cost)... I'm all ears! I'd love us to work the same way on DevTools as we do on CRUD.

Cheers!
