### ISSUE TITLE
[Bug] Compilation failed: unrecognised character

### ISSUE THREAD

**Issue by madviking** [Laravel-Backpack/devtools-issues#38]
# Bug report

### What I did

Run dev tools generate all in a custom model.

### What I expected to happen

Files to be generated.

### What happened

Some files generated, but a crash. 
https://flareapp.io/share/KPgXbZ37

### What I've already tried to fix it

I've tried that it works with a more standard model. 

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:
PHP 8.0.8 (cli) (built: Aug  5 2021 15:36:35) ( NTS )
Copyright (c) The PHP Group
Zend Engine v4.0.8, Copyright (c) Zend Technologies

### LARAVEL VERSION:
v8.79.0@8091f07558ff4a890435ff9d25fa9aca0189ad63

### BACKPACK VERSION:
5.0.6@2be4ff8407259f528a3541f0569ce156bab63165

### Operating System and Server Setup

Mamp on MacOS X

**Comment by madviking** [comment]
@tabacitu what is the general policy on dealing with the issues in this repo, as I noticed there are couple that have been without any comment for a month?

**Comment by tabacitu** [comment]
Hey @madviking ,

Sorry for the bad experience, 1-month response time on a DevTools issue isn't normal. 2022 has been a killer for us - we've tried to push Backpack v5 out the door, at the _same time_ as:
- adding Laravel 9 support to our packages
- adding Laravel 9 support to a lot of our open-source dependencies
- the regular maintenance, bug fixing and support

Now that Backpack v5 is out, and L9 support is done for _almost_ everything, things will get back to normal pretty soon.

---

I could not reproduce this. **Can you please share your migration?** Might help me re-create the same form, in order to hopefully get the same error.

Cheers!

**Comment by pxpm** [comment]
@tabacitu I guess this migth be related with MacOS. I could not reproduce it in Windows/Linux.

**Comment by tabacitu** [comment]
Since there was no response to this in a while, I'm going to close this issue. But if anybody gets a similar error:

_preg_match(): Compilation failed: unrecognized character follows \ at offset 13_

Please reply here with as much information as possible, and we'll reopen to fix it!

Thank you!
