### ISSUE TITLE
[Bug] - Unable to override ID field name

### ISSUE THREAD

**Issue by singeryo** [Laravel-Backpack/devtools-issues#44]
# Bug report

### What I did

I generated a new model using the model creation form. For the id field I kept everything as is except for the field name which I renamed. The "generate migration" and "run migration" checkboxes were checked.

### What I expected to happen

The migration should be generated with this general structure:

```
    Schema::create('flight', function (Blueprint $table) {
            $table->id('flight_id');
           // ...
    });
```

Which would result in having the ID field named properly in DB.
And the generated model should have something like this:

```
    /**
     * The primary key associated with the table.
     *
     * @var string
     */
    protected $primaryKey = 'flight_id';
```

### What happened

The ID field name override attempt was ignored and the migration was generated as so:

```
   Schema::create('flight', function (Blueprint $table) {
        $table->id();
        // ...
    });
```

### What I've already tried to fix it

My workaround is to not run the migrations automatically and edit the migration files and models manually before running the migrations. Takes some time with large number of models.

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:

```
PHP 7.4.27 (cli) (built: Dec 14 2021 19:52:13) ( ZTS Visual C++ 2017 x64 )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Xdebug v3.1.2, Copyright (c) 2002-2021, by Derick Rethans

### LARAVEL VERSION:
v8.83.9@ac6e16bb56510eda2e373c6365d5c92da3fd559d

### BACKPACK VERSION:
5.0.14@1e355c4c046a34423a1a3e3150120245a4bfd8e9

```

### Operating System and Server Setup

I encountered the problem above on my Windows 10 machine, and my web server is set up using Laragon.

**Comment by maurohmartinez** [comment]
This seems to be a tricky issue with Blueprint. I opened a [feature request](https://github.com/laravel-shift/blueprint/issues/568) to see how this can be achieved since it's not so easy to override the name for a primary column of type id.

Will add more info once I get a clear response from Blueprint's team.

**Comment by tabacitu** [comment]
I was going to suggest we disable the "id" if we don't support this. Then I thought "_why is this not disabled already_"? So I tested @singeryo 's scenario above, and... it worked for me:

https://user-images.githubusercontent.com/1032474/178975865-42113305-73f6-4f19-a777-602046d84906.mp4

I'm successfully using `key` instead of `id`. In fact, if I remember correctly, this is one customization we've had to do on top of Blueprint already. So... I don't understand exactly what @singeryo did different above... do you @maurohmartinez ?

**Comment by maurohmartinez** [comment]
@tabacitu Wow, I was testing this yesterday and it did not work. Today, after a `composer update` it works as you said.
Maybe Blueprint updated something and addressed this? I think it is working now without problems.

**Comment by tabacitu** [comment]
![idk_2](https://user-images.githubusercontent.com/1032474/179011944-59b4a04a-6930-4c9f-a859-dcaf6d674d21.gif)

The only thing we do know is that... it's working now. So @singeryo please try again after a `composer update` - it should work now. If it doesn't, please let us know and we'll reopen, dig a little deeper.

Thanks!
