### ISSUE TITLE
[Bug] new pretty console output breaks Devtools notifications

### ISSUE THREAD

**Issue by pxpm** [Laravel-Backpack/devtools-issues#49]
Run any operation in devtools ... the Notifications are not displaying properly because of the new "pretty outputs".

![image](https://user-images.githubusercontent.com/7188159/185910336-63f5c613-3d8b-4888-af8c-13aa97df25bc.png)

I've already discussed this with @promatik he's aware of the problem and will work on the solution ASAP.

**Comment by tabacitu** [comment]
Ouch! Good catch. Yes, this becomes priority no 1 @promatik 🙏

Sorry for not testing this better Pedro!

**Comment by promatik** [comment]
Hi everyone,
After discussing this with Cristian and Pedro, here are the key points to solve this;

- DevTools should not rely on console output of Generators/CRUD.
Relying on that is exponing DevTools to future breaking changes, many things can change, like new warnings or questions.
- Since Artisan commands run in a different process, we don't have access to any of `app('crud')` or events or streams, only session can be used, but it's a bit ugly to use it here.
- So the best solution we got was suggested by @pxpm, it is basically send a `--debug=.devtools` which will print into a log file, human readable, that can be later used by DevTools.
That way it is feature of Generators, and Generators are responsible to keep that output clean, human readable, so DevTools can rely on it.

**Comment by tabacitu** [comment]
Thank for the investigation @promatik . Since the bubble is no longer ugly, I've reclasified this as a COULD/SHOULD, so I'll move it to 5.4. Let's tackle more urgent issues first!
