### ISSUE TITLE
[Bug] Belongs to throws an "Database connection [articles] not configured." error.

### ISSUE THREAD

**Issue by altayevrim** [Laravel-Backpack/devtools-issues#71]
# Bug report

### What I did

I freshly installed Laravel 11 with Jetstream. I use mysql. Installed Backpack Pro with DevTools. When I try to create a model and add a column as BelongsTo type, I do receive `Database connection [articles] not configured.` (article is the table I'm trying to reference) in a modal box.

### What I expected to happen

I don't know how should the modal box actually displayed.

### What happened

??

### What I've already tried to fix it

??

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:

### PHP VERSION:
PHP 8.3.3 (cli) (built: Feb 16 2024 00:15:01) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.3.3, Copyright (c) Zend Technologies
    with Zend OPcache v8.3.3, Copyright (c), by Zend Technologies

### LARAVEL VERSION:
11.0.8.0

### BACKPACK PACKAGE VERSIONS:
backpack/basset: 1.3.0
backpack/crud: 6.7.2
backpack/devtools: 3.1.0
backpack/generators: v4.0.4
backpack/pro: 2.1.11

### Operating System and Server Setup

I encountered the problem above on my MacOS machine (Sonoma 14.4 (23E214)), and my web server is set up using Herd Pro.
Operating system and Herd freshly installed. Herd Pro is used to install MySQL service as well.

**Comment by pxpm** [comment]
Hey @altayevrim thanks for the report. 🙏 

I've just released DevTools 3.1.1 that fixes this and the other issue you reported in #72 . 

Please allow a few moments for our private repository to make the new version available and you should be able to get it with a `composer update`

In the meanwhile I am closing both issues as they should be fixed in 3.1.1, if you are still experience issues after the update please let me know and we can re-open it for further investigation. 

Thanks 🙏

**Comment by altayevrim** [comment]
You're more than a welcome! Thanks for the fast patching :) Can't wait till the update will be available.
